apiVersion: v1
kind: Service
metadata:
  name: {{ include "ec-keycloak.fullname" . }}
  labels:
    {{- include "ec-keycloak.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ec-keycloak.selectorLabels" . | nindent 4 }}
---
# Headless service for JGroups clustering
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ec-keycloak.fullname" . }}-headless
  labels:
    {{- include "ec-keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7800
      targetPort: jgroups
      protocol: TCP
      name: jgroups
  selector:
    {{- include "ec-keycloak.selectorLabels" . | nindent 4 }}
